FROM php:8.3-fpm-alpine

RUN apk add --no-cache postgresql-dev libpng-dev libzip-dev zip unzip git curl oniguruma-dev libxml2-dev

RUN docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .
RUN git config --global --add safe.directory /var/www/html
COPY docker/backend-entrypoint.sh /usr/local/bin/backend-entrypoint
RUN chmod +x /usr/local/bin/backend-entrypoint

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 9000
CMD ["/usr/local/bin/backend-entrypoint"]
